package com.malte3d.suturo.commons;

import lombok.experimental.UtilityClass;

/**
 * Utility class for version information.
 */
@UtilityClass
public class Version {

    /**
     * Determines the version of the application.
     *
     * <p>
     * The version is read from the manifest file and is generated by the build system.
     * </p>
     *
     * @return the version of the application
     */
    public static String getVersion() {
        return Version.class.getPackage().getImplementationVersion();
    }

}
