name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  JAVA_VERSION: 17

jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
      runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "$JAVA_VERSION"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - name: Run tests
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check
