name: Release

on:
  push:
    tags:
      - '*'

env:
  JAVA_VERSION: 17

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: git fetch --tags --force

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "${{ env.JAVA_VERSION }}"

      - name: Run distribution build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: distZip

      - name: Create release notes
        id: release-notes
        run: |
          echo -e "### What's changed?\n$(git tag -l --format='%(contents:body)' ${{ github.ref_name }})" > ${{ github.workspace }}-CHANGELOG.txt

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{  github.ref_name }}
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: build/distributions/*.zip